# [START runtime]
runtime: python37
automatic_scaling:
  max_instances: 1

# [END runtime]
default_expiration: 1s

# [START handlers]
handlers:
 - url: /api/.*
   script: auto
   secure: always

 - url: /static
   static_dir: myClient/build/static
   expiration: 1s
   secure: always

 - url: /(.*\.(json|ico|js))$
   static_files: myClient/build/\1
   upload: myClient/build/.*\.(json|ico|js)$
   expiration: 1s
   secure: always

 - url: .*
   static_files: myClient/build/index.html
   upload: myClient/build/index.html
   expiration: 1s
   secure: always
# [END handlers]
